### ISSUE TITLE
Unhelpful Output

### ISSUE THREAD

**Issue by bwrs** [JuvenileTapir/DebateMate#2]
Output still isn't very helpful; what we need is something cumulative, ie the chances of getting through with this score and above is x; so if you get, say, 10, you can just look and see "aha" instead of tallying 10, 11, 12, etc.
It would be like this;
7: 0%
8: x%
...
11: y%
12: 100%
(assuming say 4 rounds)

**Comment by octogenary** [comment]
This has been dealt with, at least in jdev.
